version: '3.7'

services:

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=py_bot
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pybot_postgres:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - app-network

volumes:
  pybot_postgres:

networks:
  app-network:
    driver: bridge
