"""Add car mods

Revision ID: e2d21b5f5ac0
Revises: 14c4c0966ce6
Create Date: 2023-01-08 20:48:30.789333

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from core.models import ModTypeType

# revision identifiers, used by Alembic.
revision = 'e2d21b5f5ac0'
down_revision = '14c4c0966ce6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ModTypeType.create(op.get_bind(), checkfirst=True)
    op.create_table('mod',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', ModTypeType, nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('power_add', sa.Integer(), nullable=False),
    sa.Column('order_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('order_code')
    )
    op.create_table('user_car_mod',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_car_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('mod_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['mod_id'], ['mod.id'], ),
    sa.ForeignKeyConstraint(['user_car_id'], ['user_car.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_car_mod')
    op.drop_table('mod')
    ModTypeType.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
